name: 'Replicate Docker version tag'
description: 'This action replicates Docker version tag from like `1.2.3` to `1.2` and `1`'
author: 'Yuya Takeyama'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  tag:
    required: true
    description: 'Docker image tag indicates a semver (like `1.2.3`)'
  image:
    required: false
    description: 'Docker image name (like `foo/bar` or `example.com/foo/bar`)'
  separator:
    required: false
    description: 'Separator of multiple images'
    default: ','
outputs:
  tags:
    description: 'Replicated tags'
runs:
  using: 'node12'
  main: 'dist/index.js'
